server:
  port: 8889

spring:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/, file:./data/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

logging:
  level:
    com.cloud.self.webmark: debug

webmark:
  data:
    dir: ./data